```{r}
###
# Loading libraries
###
library(tidyverse)
library(janitor)
```
Loading in data
```{r}
###
# Receipts
###
cuellar_receipts <- read_csv("data/ceullar_receipts.csv") %>%
  mutate(candidate = "Cuellar") %>%
  select(-transaction_id)
de_la_cruz_receipts <- read_csv("data/de_la_cruz_receipts.csv") %>%
  mutate(candidate = "De La Cruz") %>%
  select(-transaction_id)
flores_receipts <- read_csv("data/flores_receipts.csv") %>%
  mutate(candidate = "Flores") %>%
  select(-transaction_id)
garcia_receipts <- read_csv("data/garcia_receipts.csv") %>%
  mutate(candidate = "Garcia") %>%
  select(-transaction_id)
gonzalez_receipts <- read_csv("data/gonzalez_receipts.csv") %>%
  mutate(candidate = "Gonzalez") %>%
  select(-transaction_id)
vallejo_receipts <- read_csv("data/vallejo_receipts.csv") %>%
  mutate(candidate = "Vallejo") %>%
  select(-transaction_id)

###
# Spending
###
cuellar_spending <- read_csv("data/cuellar_spending.csv") %>%
  mutate(candidate = "Cuellar") %>%
  select(-transaction_id) %>%
  mutate(zip_code = as.numeric(zip_code))
de_la_cruz_spending <- read_csv("data/de_la_cruz_spending.csv") %>%
  mutate(candidate = "De La Cruz") %>%
  select(-transaction_id) %>%
  mutate(zip_code = as.numeric(zip_code))
flores_spending <- read_csv("data/flores_spending.csv") %>%
  mutate(candidate = "Flores") %>%
  select(-transaction_id) %>%
  mutate(zip_code = as.numeric(zip_code))
garcia_spending <- read_csv("data/garcia_spending.csv") %>%
  mutate(candidate = "Garcia") %>%
  select(-transaction_id) %>%
  mutate(zip_code = as.numeric(zip_code))
gonzalez_spending <- read_csv("data/gonzalez_spending.csv") %>%
  mutate(candidate = "Gonzalez") %>%
  select(-transaction_id) %>%
  mutate(zip_code = as.numeric(zip_code))
vallejo_spending <- read_csv("data/vallejo_spending.csv") %>%
  mutate(candidate = "Vallejo") %>%
  select(-transaction_id) %>%
  mutate(zip_code = as.numeric(zip_code))


###
# Outside spending
###
tx_15_outside <- read_csv("data/tx_15_outside_spending.csv") %>%
  mutate(district = "15") %>%
  select(committee_name, payee_name, expenditure_description, expenditure_date, expenditure_amount, candidate_name, support_oppose_indicator, district)

tx_28_outside <- read_csv("data/tx_28_outside_spending.csv") %>%
  mutate(district = "28") %>%
  select(committee_name, payee_name, expenditure_description, expenditure_date, expenditure_amount, candidate_name, support_oppose_indicator, district)

tx_34_outside <- read_csv("data/tx_34_outside_sppending.csv") %>%
  mutate(district = "34") %>%
  select(committee_name, payee_name, expenditure_description, expenditure_date, expenditure_amount, candidate_name, support_oppose_indicator, district)
```
Binding these dataframes together
```{r}
###
# Binding receipts
###

receipts_master <- cuellar_receipts %>%
  bind_rows(de_la_cruz_receipts, flores_receipts, garcia_receipts, gonzalez_receipts, vallejo_receipts)

receipts_master <- receipts_master %>%
  mutate(full_name = paste0(first_name, " ", last_name))

###
# Binding spending
###

spending_master <- cuellar_spending %>%
  bind_rows(de_la_cruz_spending, flores_spending, garcia_spending, gonzalez_spending, vallejo_spending)
```
Some exploration
```{r}
###
# Who was leading in fund raising? From where?
###

receipts_master %>%
  group_by(full_name) %>%
  summarise(total = sum(amount)) %>%
  arrange(desc(total))

###
# Who was leading in spending?
###
spending_master %>%
  group_by(candidate, purpose) %>%
  summarise(total = sum(amount)) %>%
  arrange(desc(total))
```
Binding outside spending dataframes
```{r}
outside_master <- tx_15_outside %>%
  bind_rows(tx_28_outside, tx_34_outside)

###
# How is the spending breakdown going in these districts?
###

support_oppose <- outside_master %>%
  group_by(candidate_name, support_oppose_indicator, district) %>%
  summarise(total = sum(expenditure_amount)) %>%
  arrange(desc(total))

last_week <- outside_master %>%
  filter(expenditure_date >= '2022-10-21')

support_oppose_last_week <- last_week %>%
   group_by(candidate_name, support_oppose_indicator, district) %>%
   summarise(total = sum(expenditure_amount)) %>%
   arrange(desc(total))

dems <- c("CUELLAR, HENRY", "GONZALEZ, VICENTE","GONZALEZ, VINCENTE", "CUELLAR, HENRY REP.", "VALLEJO, MICHELLE", "GONZALEZ, VICENTE REP.")
reps <- c("GARCIA, CASSANDRA", "FLORES, MAYRA", "FLORES, MAYRA NOHEMI", "GARCIA, CASSY", "DE LA CRUZ, MONICA", "FLORES, MAYRA NOHEMI", "DELACRUZ HERNANDEZ, MONICA")

x_last_week <- support_oppose_last_week %>%
  mutate(for_gop = case_when(
    candidate_name %in% dems & support_oppose_indicator == "O" ~ "y",
    candidate_name %in% dems & support_oppose_indicator == "S" ~ "n",
    candidate_name %in% reps & support_oppose_indicator == "S" ~ "y",
    candidate_name %in% reps & support_oppose_indicator == "O" ~ "n"
    ))

districts_last_week <- x_last_week %>%
  group_by(district, for_gop) %>%
  summarise(total = sum(total))

districts_last_week %>%
  group_by(district)

x_last_week %>%
  group_by(for_gop) %>%
  summarise(total = sum(total))

districts_last_week %>%
  filter(for_gop == "y") %>%
  summarise(total = sum(total))

183598.9 + 299051.9 + 300507.6

# Dem spending 2,381,355

# GOP spending 783,158.4

2381355 - 783158.4

1598197

outside_master %>%
  group_by(committee_name) %>%
  summarise(total = sum(expenditure_amount)) %>%
  arrange(desc(total))
```




